### PR TITLE
feat(compat): Add `isDate` in compat

### PR DESCRIPTION
**Pull request by chhw130**
I added `isDate` in compat layer.

### CODE REVIEW

**Comment by ssi02014** [comment]
👋 Hi! Why not separate the issue of resolving the `isEqualWith.spec.ts` error into a different pull request?

**Comment by chhw130** [comment]
> 👋 @chhw130 Hi! Why not separate the issue of resolving the `isEqualWith.spec.ts` error into a different pull request?

You're right, that makes sense. I thought it was a simple issue so I included it in this PR.
I'll create a separate PR for the `isEqualWith.spec.ts` issue. Thanks for the suggestion!

**Comment by ssi02014** [comment]
@chhw130 Cool! 👍 I suggested this because I was concerned that bundling it with the `isDate` task would delay the resolution of the `isEqualWith.spec.ts` error issue for review time. Thank you for your positive response.

**Review by raon0211 — APPROVED** [review]
Thanks!

**Pull request merged**
