### PR TITLE
test: Remove duplicated test code

### PR DESCRIPTION
**Pull request by mass2527**
I have removed the duplicate test code for `initial` and `without` that already exists in the `src/compat/array` folder.

### CODE REVIEW

**Review by raon0211 — COMMENTED** [review]
Actually the test cases in `compat` is to make sure our `compat` functions work 100% identically with `lodash`, so duplicated test code is by purpose.

**Comment by mass2527** [comment]
You're right. However, both "initial" and "without" have two test files in the `compat` folder: one in `compat/` and the other in `compat/array`. So i deleted files in `compat/`.

Is this also intentional?

**Comment by raon0211** [comment]
This is intentional to keep track of whether we have compatibility with lodash.

**Comment by mass2527** [comment]
Thanks for the explanation. I'll close this PR.

**Pull request closed without merging**
