### PR TITLE
fix(minBy): Fix typing of `minBy`

### PR DESCRIPTION
**Pull request by raviqqe**
Maybe, we should enable `noUncheckedIndexedAccess` compiler option for TypeScript too...

### CODE REVIEW

**Comment by raon0211** [comment]
Hi, you're right about the suggestion. However, our current code convention is that functions selecting an element from an array shouldn't return `undefined`. I'd like our library to return `undefined` only when noUncheckedIndexedAccess is enabled. But, as far as I know, TypeScript doesn't allow reading compiler options directly.

**Comment by raviqqe** [comment]
@raon0211 I changed the implementation to guarantee that an array length is always more than zero.

We can also allow both behaviour if it's preferrable:

```typescript
export function minBy<T>(
  items: readonly T[],
  getValue: (element: T) => number
): typeof items extends [T, ...T[]] ? T : T | undefined {
  // ...
}
```

**Comment by raon0211** [comment]
What about we use function overloading as in [head](https://es-toolkit.slash.page/reference/array/head.html)? It would be much readable.

**Comment by raviqqe** [comment]
It's ready for another review! 😄

**Review by raon0211 — APPROVED** [review]
Thanks!

**Pull request merged**
