### PR TITLE
feat(orderBy, isSymbol): add compatibility with lodash 

### LINKED ISSUE #328: orderBy keys don't support nested keys
Lodash's `orderBy` allows nested keys (`orderBy(array, ['episode.viewers'], ['asc'])`), whereas es-toolkit's `orderBy` does not.

[Example](https://stackblitz.com/edit/vitejs-vite-1zgutf?file=src%2FApp.tsx)

### PR DESCRIPTION
**Pull request by dayongkr**
## Description

I implement a `compat/orderBy`.

It is slower than `es-toolkit/orderBy`, but it is faster than `lodash/orderBy`. This is because lodash converts same strings to paths (e.g., `"user.name"` to `["user", "name"]`) during each comparison, whereas I convert the string to a path only once before sorting or comparing.

## Benchmark

Screenshot 2024-08-08 at 11 12 11 PM

close #328

### CODE REVIEW

**Comment by dayongkr** [comment]
I also implement `isSymbol`, but PR #359 also implement `isSymbol`.

**Comment by raon0211** [comment]
Let me check this during the weekend :)

**Comment by dayongkr** [comment]
> Let me check this during the weekend :)

Thanks!

And if the PR(#359) is merged, then I will fix this PR before the review.

**Review by raon0211 — APPROVED** [review]
Huge thanks for your contribution!

**Pull request merged**
