### PR TITLE
ci. fix circleCI Node.js version (20 -> 18) - fixed

### PR DESCRIPTION
**Pull request by seungrodotlee**
Based on the [documentation](https://es-toolkit.slash.page/installation.html#:~:text=es%2Dtoolkit%20supports%20Node.js%2018%20or%20later.), updating the CI to ensure compatibility with Node.js 18.

See #227.

> Closed last PR(#228) due to a mistake during the merge process.

### CODE REVIEW

**Comment by juno7803** [comment]
Then, It would be good to modify the `.nvmrc` file as well 😁
https://github.com/toss/es-toolkit/blob/2168a67045d70ed20cf52da827fb368b264bbcb8/.nvmrc#L1

**Comment by seungrodotlee** [comment]
> Then, It would be good to modify the .nvmrc file as well 😁

@juno7803 Thanks! 👍 👍

**Comment by raon0211** [comment]
Actually, I think that only the `test` job should be run on Node.js 18. (This is because I prefer to use the latest LTS version of Node.js if possible..) What are your thoughts on this?

**Comment by seungrodotlee** [comment]
> Actually, I think that only the test job should be run on Node.js 18. (This is because I prefer to use the latest LTS version of Node.js if possible..) What are your thoughts on this?

I agree with your opinion! I guess running other tasks on Node.js 20 should not have any significant impact on ensuring stability!

**Comment by seungrodotlee** [comment]
@raon0211 Rolled back the Node.js to v20 in the `.nvmrc` file and for tasks except test.

**Review by raon0211 — APPROVED** [review]
Thanks!

**Pull request merged**
