### PR TITLE
feat(memoize): add memoize

### PR DESCRIPTION
**Pull request by de-novo**
# Summary
This PR addresses the goal outlined in Issue #91 by implementing the memoize function to cache the results of function calls based on the arguments provided. Additionally, function overloads have been added to enhance flexibility and support various use cases.

# Benchmark

스크린샷 2024-07-15 오후 3 04 25

# Changes Made

### Functionality:
- Implemented the memoize function to cache function results.

### Tests:
  - Added comprehensive test cases to ensure the correctness of the memoization functionality with different overloads.
  - Verified the correct functioning of memoize with default cache, custom resolver, and custom cache.
### Documentation:
  - Updated documentation with examples demonstrating the usage of memoize with different combinations of resolvers and caches.

### CODE REVIEW

**Comment by raon0211** [comment]
Hello, this looks nice. Meanwhile, it seems that the function's implementation has become complicated to handle function overloading. The key design principle of `es-toolkit` is [simplicity](https://github.com/toss/es-toolkit/blob/main/.github/CONTRIBUTING.md#12-simplicity), to prefer implementation simplicity over handling edge cases.

Why not we get the resolver and cache by objects, and simplify our implementation?

```tsx
import { head } from '../../array/head.ts';

function memoize(func, { resolver = head, cache = new Map() }) {
  const memoized = function(...args) {
    const key = resolver(args);
    
    if (cache.has(key)) {
      return cache.get(key);
    }

    const result = func(...args);
    cache.set(result);
    return result;
  }

  memoized.cache = cache;

  return memoized;
}
```

**Comment by raon0211** [comment]
Meanwhile, I'm not sure we should accept all types of functions in our `memoize`.

Why not accept functions that take a single argument in `es-toolkit` and have users pass unary functions to our `memoize`? If we only accept unary functions, implementing `memoize` becomes straightforward.

```tsx
function memoize(func, { cache = new Map() }) {
  const memoized = function(arg) {    
    if (cache.has(arg)) {
      return cache.get(key);
    }

    const result = func(...args);
    cache.set(result);
    return result;
  }

  memoized.cache = cache;

  return memoized;
}
```

I believe this approach is much simpler and easier to read. We could implement a separate `memoize` for compatibility in `es-toolkit/compat`.

**Comment by de-novo** [comment]
> Meanwhile, I'm not sure we should accept all types of functions in our `memoize`.
> 
> Why not accept functions that take a single argument in `es-toolkit` and have users pass unary functions to our `memoize`? If we only accept unary functions, implementing `memoize` becomes straightforward.
> 
> ```tsx
> interface MemoizeOptions<P, R> {
>   cache?: Cache<P, R>;
> }
> 
> function memoize<P, R>(func: (arg: P) => R, { cache = new Map() }: MemoizeOptions<P, R> = {}) {
>   const memoized = function(arg: P): R {    
>     if (cache.has(arg)) {
>       return cache.get(key)!;
>     }
> 
>     const result = func(arg);
>     cache.set(result);
>     return result;
>   }
> 
>   memoized.cache = cache;
> 
>   return memoized;
> }
> ```
> 
> I believe this approach is much simpler and easier to read. We could implement a separate `memoize` for compatibility in `es-toolkit/compat`.

I think we need to consider the second suggestion a bit more.
```ts
```

**Comment by raon0211** [comment]
I thought using the first argument as the default key for memoization is very implicit. 

So I thought of supporting `memoize` for functions that only get a single argument; this would enable us not consider edge cases and keep the behavior straightforward.

We might support `resolver`s in our compat version of memoize, but I thought supporting functions accepting only one argument might be enough in most cases.

**Comment by de-novo** [comment]
The proposed approach to use the first argument as the default key for memoization is quite implicit. To simplify and avoid edge cases, we could support memoization only for functions that accept a single argument. This would keep the behavior straightforward.

**Comment by raon0211** [comment]
Yes, you are right. We might accept a resolver here.

**Review by raon0211 — DISMISSED** [review]
Hello, this pull request was open for a while, let me merge this and apply what we discussed earlier (making it an unary function and adding a resolver). 

Huge thanks for this contribution!

**Pull request merged**
