### PR TITLE
fix(cloneDeep):  Cannot assign to read only property '0' of object '[object String]'

### PR DESCRIPTION
**Pull request by D-Sketon**

### CODE REVIEW

**Comment by D-Sketon** [comment]
```ts
it(`should clone expando properties`, () => {
  const values = [false, true, 1, 'a'].map(value => {
    const object = Object(value);
    object.a = 1;
    return object;
  });

  const expected = values.map(stubTrue);

  const actual = values.map(value => {
    return cloneDeep(value).a === 1;
  });

  expect(actual).toEqual(expected);
});


it('should clone string objects', () => {
  const object = Object('a');

  const actual = cloneDeep(object);

  expect(actual).toEqual(object);
  expect(actual).not.toBe(object);
});
```

**Comment by D-Sketon** [comment]
Existing unit tests fail

**Comment by raon0211** [comment]
We should check for `target`'s writable property, so updated the code accordingly. Thanks for pointing this out!

**Review by raon0211 — APPROVED** [review]
Thanks!

**Pull request merged**
