### PR TITLE
feat(join): add join

### PR DESCRIPTION
**Pull request by kim-sung-jee**
# Description

add `join` function

image

### CODE REVIEW

**Comment by dayongkr** [comment]
We already have a native api(Array.prototype.join), so maybe it needs only in es-toolkit/compat.

**Comment by kim-sung-jee** [comment]
I understand that the es-toolkit may not include a join function as a feature. 
Does that seem correct?

**Comment by dayongkr** [comment]
You can see a same case in [here(`es-toolkit/compat/concat`)](https://es-toolkit.slash.page/reference/compat/array/concat.html).

> This function is only available in es-toolkit/compat for compatibility reasons. It either has alternative native JavaScript APIs or isn’t fully optimized yet.

I hope this information is helpful.

**Comment by kim-sung-jee** [comment]
@dayongkr 

oh thank you!
I'll close the PR.

**Comment by dayongkr** [comment]
I think that you open the PR again after changing PR for adding `es-toolkit/compat/join`! Thank you!

And I think that you don't have to close this PR.

We have to decide this after reviewing @raon0211.

**Comment by dayongkr** [comment]
I think that you don't have to close this PR at now, it is just my opinion.

Maybe, you decide whether close or not after reviewing @raon0211.

Thanks!

**Pull request closed without merging**
