### PR TITLE
feat(flattenObject): add flattenObject for flatten object keys

### PR DESCRIPTION
**Pull request by ngthuongdoan**

### CODE REVIEW

**Comment by ngthuongdoan** [comment]
Related #142

**Comment by raon0211** [comment]
Sorry for the late review. The implementation is a little bit hard for me to read. Please let me some time to add the review (Recently, a lot of pull requests and issues are springing up.)

**Comment by raon0211** [comment]
Hello, thanks for your pull request! I understand the needs for `flattenObject`.

Meanwhile, I think we have to implement `flattenObject` in an other way for these reasons:
- The current implementation uses `lodash`, which is what we prohibit, since using lodash from es-toolkit does not make sense.
- The current implementation is a bit complex to understand, while our core values of the library is [simplicity](https://github.com/toss/es-toolkit/blob/main/.github/CONTRIBUTING.md#12-simplicity).

Let me work on implementing `flattenObject` asap.

**Comment by raon0211** [comment]
Implemented `flattenObject` in this commit. Thanks for giving us ideas!

https://github.com/toss/es-toolkit/commit/3e60443a408d3296e4a18a1601a16f5953d414f9

**Pull request closed without merging**
