### PR TITLE
feat(takeRightWhile): Add `takeRightWhile` to compat

### PR DESCRIPTION
**Pull request by mass2527**

### CODE REVIEW

**Review by raon0211 — DISMISSED** [review]
Great work! Thanks for your help!

**Comment by raon0211** [comment]
Seems that types and tests are failing..

image

**Review by raon0211 — APPROVED** [review]
Thanks!

**Comment by mass2527** [comment]
sorry, fixed in this [commit](https://github.com/toss/es-toolkit/pull/877/commits/5d87cd29e2dd94c7bceb287f34a92a0843d02c33).

> Seems that types and tests are failing..
> 
> image

**Comment by raon0211** [comment]
No need to be sorry :)

**Pull request merged**
