### PR TITLE
feat(cloneDeep): add cloneDeep

### PR DESCRIPTION
**Pull request by de-novo**
## Summary

This PR addresses [Issue #140](https://github.com/toss/es-toolkit/issues/140) by implementing the cloneDeep function to create deep copies of objects, arrays, and other complex data types.

## Benchmark
스크린샷 2024-07-15 오전 8 29 26

## Changes Made
- Functionality: Added cloneDeep to deeply clone objects, arrays, dates, regex, maps, sets, and more.	
- Tests: Added comprehensive test cases to ensure the correctness of the deep cloning functionality.
- Documentation: Updated documentation with examples demonstrating the usage of cloneDeep.
- Benchmarking: Added benchmarks comparing cloneDeep performance with similar functions.

## Considerations
In the current implementation, cloneDeep supports deep cloning of instances, allowing instance methods to be used after cloning. In contrast, the existing library’s clone function does not allow the use of class methods on deeply cloned instances, even though IDEs can infer the methods. This discrepancy can cause significant confusion during development. To address this, the implementation ensures that instances are fully cloned, preserving the functionality of their methods.

For more details, please refer to [PR #155](https://github.com/toss/es-toolkit/pull/155).

### CODE REVIEW

**Comment by samchon** [comment]
@de-novo I think it would better to change to `cloneDeep()` function to return `Resolved<T>` type.

Also, it would better to consider more native classes case.

- `Resolved<T>` type: https://github.com/samchon/typia/blob/master/src/Resolved.ts
- Clone function of other library (does not consider `RegExp` type): https://github.com/samchon/typia/blob/master/src/functional/%24clone.ts

**Comment by bovas85** [comment]
note/bug/support issue:
This does not seem to work with Events
image

**Comment by raon0211** [comment]
We discussed that we use `structuredClone` rather than re-implementating deep clones. (See https://github.com/toss/es-toolkit/issues/140)

 Is it more performant to implement `cloneDeep` ourselves?

**Comment by de-novo** [comment]
@samchon Thank you for your valuable feedback. We have applied the changes to the cloneDeep function to return the Resolved<T> type, as well as considered more native class cases. We appreciate your suggestions and have implemented them accordingly!

**Comment by de-novo** [comment]
@bovas85 Thank you for your feedback! I have resolved the current issue related to cloning Event objects. However, the modified code now returns an empty object {} when attempting to clone Web spec classes like Event. While I tried to incorporate other Web API specifications similar to Event, the extensive number of cases within the Web API specifications makes fully supporting all of them practically unfeasible at this time.

Initially, I aimed to clone class instances such that instance => instance. However, due to the inability to access #private members, I have shifted to using the structuredClone specification.

**Comment by de-novo** [comment]
@raon0211 The benchmark results show that the cloneDeep function is approximately twice as fast as Node’s structuredClone.  
스크린샷 2024-07-17 오전 10 50 00

**Comment by bovas85** [comment]
> @bovas85 Thank you for your feedback! I have resolved the current issue related to cloning Event objects. However, the modified code now returns an empty object {} when attempting to clone Web spec classes like Event. While I tried to incorporate other Web API specifications similar to Event, the extensive number of cases within the Web API specifications makes fully supporting all of them practically unfeasible at this time.
> 
> Initially, I aimed to clone class instances such that instance => instance. However, due to the inability to access #private members, I have shifted to using the structuredClone specification.

Sounds good. I'll test tomorrow and let you know if it solves it with the extra cases added

**Comment by seungrodotlee** [comment]
image

Similar to the case in #206, it returns an error in Node v18.

**Comment by de-novo** [comment]
> image
> 
> Similar to the case in #206, it returns an error in Node v18.

@seungrodotlee  Fixed the problem

**Review by raon0211 — DISMISSED** [review]
Let me merge this, and make the type of `cloneDeep` a little simpler.

We might discuss the `Resolved<T>` type in the following pull request: https://github.com/toss/es-toolkit/pull/206.

**Pull request merged**
