### PR TITLE
feat(take): Add default `count` parameter to `take`

### PR DESCRIPTION
**Pull request by mass2527**
I think `take` function should also have default `count` parameter like [`takeRight`](https://github.com/toss/es-toolkit/blob/main/src/array/takeRight.ts)

lodash [`take`](https://lodash.com/docs/4.17.15#take) and [`takeRight`](https://lodash.com/docs/4.17.15#takeRight) both have default parameter.

### CODE REVIEW

**Comment by raon0211** [comment]
Actually, if `takeRight` has a default parameter, it is not what we intended. We would like our users to provide explicit arguments to our functions.

**Comment by mass2527** [comment]
@raon0211 
Thanks for reviewing.

I assumed that the es-toolkit decided to add a default parameter, similar to lodash, since [takeRight](https://github.com/toss/es-toolkit/blob/main/src/array/takeRight.ts) already had one. If this wasn't intentional, we might consider removing the default parameter from `takeRight`.

**Comment by raon0211** [comment]
Yes, that's right. We might remove the default parameter from `takeRight` -- that was by accident.

**Comment by mass2527** [comment]
then i will close this PR and make another pull request that remove default parameter from `takeRight`

**Pull request closed without merging**
