### PR TITLE
feat(cloneDeep): add custom rules support and test cases

### PR DESCRIPTION
**Pull request by jacksonyu**
implement #367

### CODE REVIEW

**Comment by raon0211** [comment]
Hello, thanks for your pull request! 

While I think this is a use case what we should support, I am not sure this interface is best. Could you let me think about the interface?

**Comment by jacksonyu** [comment]
> Hello, thanks for your pull request!
> 
> While I think this is a use case what we should support, I am not sure this interface is best. Could you let me think about the interface?

of course. 
This is how lodash implements this feature: [cloneDeepWith](https://www.lodashjs.com/docs/lodash.cloneDeepWith).
But I think a arrray of  custom rules would make this feature implementations more modular.

**Comment by bytenik** [comment]
I need this for a project I'm currently working on. Is there a chance this could get merged soon @raon0211?

**Comment by raon0211** [comment]
Hello, `cloneDeepWith` was added in es-toolkit v1.29.0. You can customize how to clone values.

https://es-toolkit.slash.page/reference/object/cloneDeepWith.html

Closing the pull request for now :)

**Pull request closed without merging**
