### PR TITLE
fix: correct typos

### PR DESCRIPTION
**Pull request by mass2527**
What do you think about adding a [code spell checker](https://marketplace.visualstudio.com/items?itemName=streetsidesoftware.code-spell-checker) to the VSCode's recommended extensions?
I believe it could help prevent typos.

### CODE REVIEW

**Comment by raon0211** [comment]
Yeah, adding the vscode extension would help!

**Comment by raon0211** [comment]
Additionally, if we had CI to check for typos, it would also help.

**Review by raon0211 — APPROVED** [review]
Thanks!

**Comment by mass2527** [comment]
Okay, I will add an ESLint plugin for this.

**Pull request merged**
